export const labels = {
  ar: {
    heading: 'اتفاقات الشراء', intro: 'عرض واضح للكورس، الموارد، السعر وشروط الدفع في رابط واحد.',
    load: 'تحميل / تحديث الاتفاقات', create: 'اتفاق جديد', empty: 'لا توجد اتفاقات بعد.', edit: 'تعديل', copy: 'نسخ الرابط', open: 'فتح الاتفاق', publish: 'نشر النسخة المحفوظة',
    title: 'اسم العرض / عنوان الاتفاق', description: 'وصف الكورس', includes: 'ما يتضمنه الكورس', resources: 'الموارد والمصادر التي يحصل عليها المشتري', refund: 'شروط استرجاع المبلغ', paymentMethod: 'طريقة الدفع', paymentInstructions: 'تعليمات الدفع',
    language: 'لغة الاتفاق الافتراضية', translation: 'المحتوى العربي والفرنسي', translationNote: 'أكمل حقول اللغة الافتراضية. اللغة الثانية اختيارية؛ إذا أضفتها فأكمل جميع حقولها. كل سطر في المحتويات والموارد يمثل بندًا.',
    visibility: 'نوع الرابط', private: 'خاص — مشفّر لحامل الرابط', public: 'عام — محتوى منشور للجميع', privacy: 'الرابط الخاص يفتح لمن يملك الرابط الكامل ويمكن إعادة مشاركته. الاتفاق العام يُحفظ في مستودع عام وسجل تعديلاته. لا يمكن تغيير النوع بعد الحفظ.',
    total: 'السعر الإجمالي', currency: 'العملة', count: 'عدد الدفعات', amount: 'قيمة الدفعة', date: 'تاريخ الاستحقاق', paymentUrl: 'رابط الدفع HTTPS (اختياري)',
    safety: 'اكتب وصف طريقة الدفع أو تعليماتها فقط. لا تدخل أرقام بطاقات، CVV، كلمات مرور، مفاتيح API أو بيانات بروكسي حساسة.',
    save: 'حفظ ونشر الاتفاق', cancel: 'إغلاق المحرر', saving: 'جارٍ الحفظ والنشر…', loading: 'جارٍ تحميل الاتفاقات…', saved: 'حُفظ الاتفاق وأُرسل للنشر. قد يستغرق ظهوره على GitHub Pages بضع دقائق.',
    partial: 'حُفظ الاتفاق في المستودع الخاص، لكن النشر لم يكتمل. استخدم «نشر النسخة المحفوظة» لإعادة المحاولة دون إنشاء رابط جديد.', copied: 'تم نسخ الرابط.', copyFailed: 'تعذر النسخ التلقائي. انسخ الرابط الظاهر يدويًا.', revision: 'النسخة', updated: 'آخر تحديث',
    notice: 'هذا العرض يوضح المحتوى والسعر وشروط الدفع. عرض الصفحة لا يؤكد إجراء الدفع أو قبول الاتفاق، ولا يمنح رابط دخول للكورس.',
    agreement: 'اتفاق شراء', schedule: 'جدول الدفعات', installment: 'الدفعة', pay: 'الانتقال إلى الدفع', print: 'طباعة / حفظ PDF', unavailable: 'تعذر فتح الاتفاق. تحقق من الرابط الكامل أو انتظر اكتمال النشر ثم أعد المحاولة.', retry: 'إعادة المحاولة',
    errors: { required: 'أكمل جميع حقول كل لغة مستخدمة، مع احترام الطول المسموح.', money: 'أدخل مبالغ موجبة بدقة العملة (منزلتان، أو ثلاث للدينار التونسي).', count: 'عدد الدفعات يجب أن يكون بين 1 و36.', date: 'أدخل تواريخ صحيحة مرتبة من الأقدم إلى الأحدث.', sum: 'مجموع الدفعات يجب أن يساوي السعر الإجمالي.', url: 'رابط الدفع يجب أن يبدأ بـ HTTPS وألا يحتوي على اسم مستخدم أو كلمة مرور.', sensitive: 'يبدو أن المحتوى يتضمن بيانات دفع أو بيانات دخول حساسة. احذفها قبل الحفظ.', conflict: 'توجد تعديلات أحدث. حدّث قائمة الاتفاقات وافتح النسخة الجديدة قبل الحفظ.', visibility: 'لا يمكن تغيير نوع الرابط بعد الحفظ. أنشئ اتفاقًا جديدًا.', invalid: 'بيانات الاتفاق غير صالحة.', network: 'تعذر تنفيذ العملية. تحقق من الاتصال وصلاحيات المستودعين ثم أعد المحاولة.' }
  },
  fr: {
    heading: 'Accords d’achat', intro: 'La formation, les ressources, le prix et les modalités de paiement réunis dans un lien.',
    load: 'Charger / actualiser les accords', create: 'Nouvel accord', empty: 'Aucun accord pour le moment.', edit: 'Modifier', copy: 'Copier le lien', open: 'Ouvrir l’accord', publish: 'Publier la version enregistrée',
    title: 'Nom de l’offre / titre de l’accord', description: 'Description de la formation', includes: 'Contenu de la formation', resources: 'Ressources et sources fournies à l’acheteur', refund: 'Conditions de remboursement', paymentMethod: 'Moyen de paiement', paymentInstructions: 'Instructions de paiement',
    language: 'Langue par défaut de l’accord', translation: 'Contenu arabe et français', translationNote: 'Complétez tous les champs de la langue par défaut. La seconde langue est facultative ; si vous l’ajoutez, complétez tous ses champs. Une ligne par élément de contenu ou ressource.',
    visibility: 'Type de lien', private: 'Privé — chiffré pour le détenteur du lien', public: 'Public — contenu accessible à tous', privacy: 'Toute personne possédant le lien privé complet peut l’ouvrir et le partager. Un accord public est enregistré dans un dépôt public, avec son historique. Le type ne peut plus être modifié après enregistrement.',
    total: 'Prix total', currency: 'Devise', count: 'Nombre d’échéances', amount: 'Montant de l’échéance', date: 'Date d’échéance', paymentUrl: 'Lien de paiement HTTPS (facultatif)',
    safety: 'Indiquez uniquement le moyen de paiement et ses instructions. Ne saisissez ni numéro de carte, CVV, mot de passe, clé API, ni identifiants de proxy.',
    save: 'Enregistrer et publier', cancel: 'Fermer l’éditeur', saving: 'Enregistrement et publication…', loading: 'Chargement des accords…', saved: 'Accord enregistré et envoyé à la publication. Sa disponibilité sur GitHub Pages peut prendre quelques minutes.',
    partial: 'L’accord est enregistré dans le dépôt privé, mais sa publication a échoué. Utilisez « Publier la version enregistrée » pour réessayer en conservant le même lien.', copied: 'Lien copié.', copyFailed: 'Copie automatique impossible. Copiez manuellement le lien affiché.', revision: 'Version', updated: 'Dernière mise à jour',
    notice: 'Cette offre présente le contenu, le prix et les modalités de paiement. Consulter cette page ne confirme ni un paiement ni l’acceptation de l’accord, et ne donne pas accès à la formation.',
    agreement: 'Accord d’achat', schedule: 'Échéancier de paiement', installment: 'Échéance', pay: 'Accéder au paiement', print: 'Imprimer / enregistrer en PDF', unavailable: 'Impossible d’ouvrir cet accord. Vérifiez le lien complet ou attendez la fin de la publication, puis réessayez.', retry: 'Réessayer',
    errors: { required: 'Complétez tous les champs de chaque langue utilisée et respectez leur longueur maximale.', money: 'Saisissez des montants positifs avec deux décimales au maximum (trois pour le dinar tunisien).', count: 'Le nombre d’échéances doit être compris entre 1 et 36.', date: 'Saisissez des dates valides dans l’ordre chronologique.', sum: 'La somme des échéances doit être égale au prix total.', url: 'Le lien de paiement doit utiliser HTTPS, sans identifiant ni mot de passe.', sensitive: 'Le contenu semble inclure des données de paiement ou des identifiants sensibles. Supprimez-les avant l’enregistrement.', conflict: 'Une version plus récente existe. Actualisez la liste et ouvrez cette version avant d’enregistrer.', visibility: 'Le type de lien ne peut plus être modifié. Créez un nouvel accord.', invalid: 'Les données de l’accord sont invalides.', network: 'Opération impossible. Vérifiez la connexion et les autorisations des deux dépôts, puis réessayez.' }
  }
};
